# Generated by Django 5.2.5 on 2025-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='petition_images/')),
                ('reason', models.TextField()),
                ('yes_votes', models.PositiveIntegerField()),
                ('no_votes', models.PositiveIntegerField()),
            ],
        ),
    ]
