# Generated by Django 5.2.5 on 2025-09-27 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_petitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petition',
            name='no_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petition',
            name='yes_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
