# Generated by Django 5.2.5 on 2025-09-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='stock',
        ),
    ]
